from __future__ import annotations
 
import asyncio
import logging
import os
import signal
import sys
from datetime import datetime
 
from google.adk.agents import SequentialAgent
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
 
from pipeline.agents import AnalyzeAgent, DecisionAgent, ActionAgent, ImprovementAgent
from pipeline.tools.reactor_tools import init_tools, set_ai_mode, set_backup
 
logger = logging.getLogger(__name__)
 

# default initial session state
# generated by claude highkey
DEFAULT_STATE: dict = {

    # ── Current sensor snapshot ───────────────────────────────────────────
    # Written by AnalyzeAgent every cycle
    "raw_adc":     0,
    "electrode_a": 0,
    "electrode_b": 0,

    # ── Cycle tracking ────────────────────────────────────────────────────
    # cycle_count: incremented at top of every AnalyzeAgent run
    # last_command_cycle: stamped by ActionAgent on real command,
    #                     and by AnalyzeAgent on target change
    # Both start at 0 so cycle 1 gives cycles_since_command = 1,
    # which is correct (no command has ever fired yet)
    "cycle_count":        0,
    "last_command_cycle": 0,

    # ── Tuning parameters (live) ──────────────────────────────────────────
    # These are the values AnalyzeAgent reads at the top of every cycle.
    # ImprovementAgent updates them and pushes changes to Arduino via set_params.
    #
    # target_adc:      752  — 75% of usable ADC range (550 + 270*0.75)
    #                         Not max — leaves headroom to correct upward.
    #                         ImprovementAgent pushes this higher as beam stabilises.
    #
    # max_delta:       200  — max DAC step per cycle
    #                         200 counts * (12V / 4095) ≈ 586mV per cycle
    #                         ~5% of full DAC range — coarse enough to find beam,
    #                         fine enough not to overshoot badly
    #
    # spike_threshold: 800  — ADC above this = likely arc discharge in vacuum tube
    #                         5% safety margin below PHOTO_MAX of 820
    #                         triggers emergency_backup immediately
    #
    # low_threshold:   580  — ADC below this = beam not found or lost
    #                         just above PHOTO_MIN of 550
    #                         at startup this is expected (beam search mode)
    #
    # settle_timeout:  8    — max cycles to wait after a command before forcing
    #                         is_settling=False regardless of tail range
    #                         at 1s cycle rate = 8 seconds max wait
    #                         set above physical HV boost converter settle time
    #
    # settling_threshold: 5.0 — tail range (ADC counts) above which signal is
    #                           considered still moving
    #                           set above noise floor (~3 counts after Arduino
    #                           10-sample averaging)
    "target_adc":         752,
    "max_delta":          200,
    "spike_threshold":    800,
    "low_threshold":      580,
    "settle_timeout":     8,
    "settling_threshold": 5.0,

    # ── Pipeline state ────────────────────────────────────────────────────
    # Empty dicts so agents can always safely call .get() on these
    # without KeyError on cycle 1
    "analysis":           {},
    "decision":           {},
    "last_action":        {},
    "improvement_result": {},

    # ── History ───────────────────────────────────────────────────────────
    # Each entry snapshots target_adc at the moment of the reading
    # so integral_error stays valid across ImprovementAgent target changes.
    # Capped at MAX_HISTORY = 50 entries by AnalyzeAgent.
    "history": [],

    # ── LLM prompt staging ────────────────────────────────────────────────
    # Throwaway strings written before each LLM call.
    # Exclude from any persistent session backend serialisation.
    "_decision_prompt":    "",
    "_improvement_prompt": "",
}

# whole pipeline sequential flow typeshit
def build_pipeline(model: str = "gemini-2.5-flash-lite") -> SequentialAgent:
    return SequentialAgent(
        name="fusion_cycle",
        description="One full sense→decide→act→improve cycle for the fusion reactor.",
        sub_agents=[
            AnalyzeAgent(),
            DecisionAgent(model=model),
            ActionAgent(),
            ImprovementAgent(model=model),
        ],
    )

# handles startup, shutdown, per cycle stuff
#infinite loop
# lowkey just boilerplate code
class FusionPipelineRunner:

    APP_NAME   = "fusion_reactor"
    USER_ID    = "system"
    SESSION_ID = "main_session"

    def __init__(
        self,
        bridge, # basically either simulated bridge or the serial bridge
        model: str = "gemini-2.5-flash-lite",
        initial_state: dict | None = None,
        max_consecutive_errors: int = 5,      # ← add this
    ):
        self._bridge                 = bridge
        self._model                  = model
        self._initial_state          = initial_state or DEFAULT_STATE.copy()
        self._running                = False
        self._max_consecutive_errors = max_consecutive_errors   # ← store it

        self._session_service = InMemorySessionService()
        self._pipeline        = build_pipeline(model=model)
        self._runner          = Runner(
            agent=self._pipeline,
            app_name=self.APP_NAME,
            session_service=self._session_service,
        )

 
    # sets the session state loll and starts the adk sht
    async def _create_session(self):
        await self._session_service.create_session(
            app_name=self.APP_NAME,
            user_id=self.USER_ID,
            session_id=self.SESSION_ID,
            state=self._initial_state.copy(),
        )
        logger.info("ADK session created: %s / %s", self.USER_ID, self.SESSION_ID)
 
    # execute one full cycle 
    async def _run_one_cycle(self, cycle: int):
        from google.genai.types import Content, Part
 
       
        # adk is funky as hell and needs a user msg to trigger
        # uses a single clock tick message, all good bc state has stuff we need
        tick_msg = Content(
            parts=[Part(text=f"cycle={cycle} ts={datetime.utcnow().isoformat()}")],
            role="user",
        )
 
        async for event in self._runner.run_async(
            user_id=self.USER_ID,
            session_id=self.SESSION_ID,
            new_message=tick_msg,
        ):
            # log significant events
            author = getattr(event, "author", "?")
            if hasattr(event, "content") and event.content:
                parts = event.content.get("parts", [])
                for part in parts:
                    if "text" in part and part["text"].strip():
                        logger.debug("[%s] %s", author, part["text"].strip()[:200])
 
    # execute infinite full cycle 
    async def run_forever(self):
        init_tools(self._bridge)
        await self._create_session()

        set_ai_mode()
        logger.info("Arduino switched to AI mode")

        self._running      = True
        cycle              = 0
        consecutive_errors = 0

        logger.info("=== Fusion Pipeline Started ===")
        try:
            while self._running:
                cycle += 1
                logger.info("── Cycle %d ──────────────────────────────────", cycle)
                try:
                    await self._run_one_cycle(cycle)
                    consecutive_errors = 0   # reset on any successful cycle
                except asyncio.CancelledError:
                    raise
                except Exception as exc:
                    consecutive_errors += 1
                    logger.error(
                        "Cycle %d error (%d/%d): %s",
                        cycle, consecutive_errors,
                        self._max_consecutive_errors, exc,
                        exc_info=True,
                    )
                    if consecutive_errors >= self._max_consecutive_errors:
                        logger.critical(
                            "%d consecutive failures — unrecoverable, shutting down",
                            self._max_consecutive_errors,
                        )
                        self._running = False
                    else:
                        await asyncio.sleep(2.0)

        except asyncio.CancelledError:
            logger.info("Pipeline cancelled")
        finally:
            await self._shutdown()
 
    # switches to backup
    async def _shutdown(self):
        logger.info("Shutting down — switching Arduino to auto/backup mode")
        try:
            set_backup()
        except Exception as exc:
            logger.warning("Could not switch to backup mode: %s", exc)
        self._running = False
        logger.info("=== Fusion Pipeline Stopped ===")
 
    # stops loop fully
    def stop(self):
        self._running = False