from __future__ import annotations
 
import asyncio
import logging
import os
import signal
import sys
from datetime import datetime
 
from google.adk.agents import SequentialAgent
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
 
from pipeline.agents import AnalyzeAgent, DecisionAgent, ActionAgent, ImprovementAgent
from pipeline.tools.reactor_tools import init_tools, set_ai_mode, set_backup
 
logger = logging.getLogger(__name__)
 

# default initial session state
# generated by claude highkey
DEFAULT_STATE: dict = {

    # ── Current sensor snapshot ───────────────────────────────────────────
    # Written by AnalyzeAgent every cycle
    "raw_adc":     0,
    "electrode_a": 0,
    "electrode_b": 0,

    # ── Cycle tracking ────────────────────────────────────────────────────
    # cycle_count: incremented at top of every AnalyzeAgent run
    # last_command_cycle: stamped by ActionAgent on real command,
    #                     and by AnalyzeAgent on target change
    # Both start at 0 so cycle 1 gives cycles_since_command = 1,
    # which is correct (no command has ever fired yet)
    "cycle_count":        0,
    "last_command_cycle": 0,

    # ── Tuning parameters (live) ──────────────────────────────────────────
    # These are the values AnalyzeAgent reads at the top of every cycle.
    # ImprovementAgent updates them and pushes changes to Arduino via set_params.
    #
    # target_adc:      752  — 75% of usable ADC range (550 + 270*0.75)
    #                         Not max — leaves headroom to correct upward.
    #                         ImprovementAgent pushes this higher as beam stabilises.
    #
    # max_delta:       200  — max DAC step per cycle
    #                         200 counts * (12V / 4095) ≈ 586mV per cycle
    #                         ~5% of full DAC range — coarse enough to find beam,
    #                         fine enough not to overshoot badly
    #
    # spike_threshold: 800  — ADC above this = likely arc discharge in vacuum tube
    #                         5% safety margin below PHOTO_MAX of 820
    #                         triggers emergency_backup immediately
    #
    # low_threshold:   580  — ADC below this = beam not found or lost
    #                         just above PHOTO_MIN of 550
    #                         at startup this is expected (beam search mode)
    #
    # settle_timeout:  8    — max cycles to wait after a command before forcing
    #                         is_settling=False regardless of tail range
    #                         at 1s cycle rate = 8 seconds max wait
    #                         set above physical HV boost converter settle time
    #
    # settling_threshold: 5.0 — tail range (ADC counts) above which signal is
    #                           considered still moving
    #                           set above noise floor (~3 counts after Arduino
    #                           10-sample averaging)
    "target_adc":         752,
    "max_delta":          200,
    "spike_threshold":    800,
    "low_threshold":      580,
    "settle_timeout":     8,
    "settling_threshold": 5.0,

    # ── Pipeline state ────────────────────────────────────────────────────
    # Empty dicts so agents can always safely call .get() on these
    # without KeyError on cycle 1
    "analysis":           {},
    "decision":           {},
    "last_action":        {},
    "improvement_result": {},

    # ── History ───────────────────────────────────────────────────────────
    # Each entry snapshots target_adc at the moment of the reading
    # so integral_error stays valid across ImprovementAgent target changes.
    # Capped at MAX_HISTORY = 50 entries by AnalyzeAgent.
    "history": [],

    # ── LLM prompt staging ────────────────────────────────────────────────
    # Throwaway strings written before each LLM call.
    # Exclude from any persistent session backend serialisation.
    "_decision_prompt":    "",
    "_improvement_prompt": "",
}

# whole pipeline 
def build_pipeline(model: str = "gemini-2.5-flash-lite") -> SequentialAgent:
    return SequentialAgent(
        name="fusion_cycle",
        description="One full sense→decide→act→improve cycle for the fusion reactor.",
        sub_agents=[
            AnalyzeAgent(),
            DecisionAgent(model=model),
            ActionAgent(),
            ImprovementAgent(model=model),
        ],
    )