from __future__ import annotations

import asyncio
import logging
import os
import signal
import sys
from datetime import datetime

from google.adk.agents import SequentialAgent
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService

from pipeline.agents.analyze_agent import AnalyzeAgent
from pipeline.agents.decision_agent import DecisionAgent
from pipeline.agents.action_agent import ActionAgent
from pipeline.agents.improvement_agent import ImprovementAgent

from pipeline.tools.reactor_tools import init_tools, set_ai_mode, set_backup

try:
    from websocket_bridge import broadcast_state
    WEBSOCKET_ENABLED = True
except ImportError:
    WEBSOCKET_ENABLED = False
    logger.warning("WebSocket bridge not available — frontend updates disabled")

logger = logging.getLogger(__name__)
 

# default initial session state
# generated by claude highkey
DEFAULT_STATE: dict = {

    # ── Current sensor snapshot ───────────────────────────────────────────
    # Written by AnalyzeAgent every cycle
    "raw_adc":     0,
    "electrode_a": 0,
    "electrode_b": 0,

    # ── Cycle tracking ────────────────────────────────────────────────────
    # cycle_count: incremented at top of every AnalyzeAgent run
    # last_command_cycle: stamped by ActionAgent on real command,
    #                     and by AnalyzeAgent on target change
    # Both start at 0 so cycle 1 gives cycles_since_command = 1,
    # which is correct (no command has ever fired yet)
    "cycle_count":        0,
    "last_command_cycle": 0,

    # ── Tuning parameters (live) ──────────────────────────────────────────
    # These are the values AnalyzeAgent reads at the top of every cycle.
    # ImprovementAgent updates them and pushes changes to Arduino via set_params.
    #
    # target_adc:      600  — starts just above low_threshold (580), giving the
    #                         system an achievable initial setpoint at low DAC values.
    #                         ImprovementAgent pushes this upward as the beam stabilises.
    #                         Previous value of 752 caused integral_error = −540 in the
    #                         first 20 cycles (every reading of ~580 vs target 752),
    #                         which poisoned the chronic-undershoot detector and caused
    #                         ImprovementAgent to make aggressive parameter changes early.
    #
    # max_delta:       200  — max DAC step per cycle
    #                         200 counts * (12V / 4095) ≈ 586mV per cycle
    #                         ~5% of full DAC range — coarse enough to find beam,
    #                         fine enough not to overshoot badly
    #
    # spike_threshold: 800  — ADC above this = likely arc discharge in vacuum tube
    #                         5% safety margin below PHOTO_MAX of 820
    #                         triggers emergency_backup immediately
    #
    # low_threshold:   580  — ADC below this = beam not found or lost
    #                         just above PHOTO_MIN of 550
    #                         at startup this is expected (beam search mode)
    #
    # settle_timeout:  8    — max cycles to wait after a command before forcing
    #                         is_settling=False regardless of tail range
    #                         at 1s cycle rate = 8 seconds max wait
    #                         set above physical HV boost converter settle time
    #
    # settling_threshold: 5.0 — tail range (ADC counts) above which signal is
    #                           considered still moving
    #                           set above noise floor (~3 counts after Arduino
    #                           10-sample averaging)
    "target_adc":         600,
    "max_delta":          200,
    "spike_threshold":    800,
    "low_threshold":      580,
    "settle_timeout":     8,
    "settling_threshold": 5.0,

    # ── Pipeline state ────────────────────────────────────────────────────
    # Empty dicts so agents can always safely call .get() on these
    # without KeyError on cycle 1
    "analysis":           {},
    "decision":           {},
    "last_action":        {},
    "improvement_result": {},

    # ── History ───────────────────────────────────────────────────────────
    # Each entry snapshots target_adc at the moment of the reading
    # so integral_error stays valid across ImprovementAgent target changes.
    # Capped at MAX_HISTORY = 50 entries by AnalyzeAgent.
    "history": [],

    # ── Decision history ──────────────────────────────────────────────────
    # Rolling log of the last 10 decisions (action + deltas + cycle).
    # Injected into DecisionAgent and ImprovementAgent prompts so the LLMs
    # can see what actually happened in recent cycles and stop reasoning
    # as if it's cycle 1.
    "decision_history": [],

    # ── LLM prompt staging ────────────────────────────────────────────────
    # Throwaway strings written before each LLM call.
    # Exclude from any persistent session backend serialisation.
    "_decision_prompt":    "",
    "_improvement_prompt": "",
}

# whole pipeline sequential flow typeshit
def build_pipeline(model: str = "gemini-2.5-flash-lite") -> SequentialAgent:
    return SequentialAgent(
        name="fusion_cycle",
        description="One full sense→decide→act→improve cycle for the fusion reactor.",
        sub_agents=[
            AnalyzeAgent(),
            DecisionAgent(model=model),
            ActionAgent(),
            ImprovementAgent(model=model),
        ],
    )

# handles startup, shutdown, per cycle stuff
#infinite loop
# lowkey just boilerplate code
class FusionPipelineRunner:

    APP_NAME   = "fusion_reactor"
    USER_ID    = "system"
    SESSION_ID = "main_session"

    def __init__(
        self,
        bridge, # basically either simulated bridge or the serial bridge
        model: str = "gemini-2.5-flash-lite",
        initial_state: dict | None = None,
        max_consecutive_errors: int = 5,      # ← add this
    ):
        self._bridge                 = bridge
        self._model                  = model
        self._initial_state          = initial_state or DEFAULT_STATE.copy()
        self._running                = False
        self._max_consecutive_errors = max_consecutive_errors   # ← store it

        self._session_service = InMemorySessionService()
        self._pipeline        = build_pipeline(model=model)
        self._runner          = Runner(
            agent=self._pipeline,
            app_name=self.APP_NAME,
            session_service=self._session_service,
        )



    # sets the session state and starts the adk session
    async def _create_session(self):
        await self._session_service.create_session(
            app_name=self.APP_NAME,
            user_id=self.USER_ID,
            session_id=self.SESSION_ID,
            state=self._initial_state.copy(),
        )
        logger.info("ADK session created: %s / %s", self.USER_ID, self.SESSION_ID)
 
    # execute one full cycle
    async def _run_one_cycle(self, cycle: int):
        from google.genai.types import Content, Part

        # ADK needs a user message to trigger the pipeline each cycle.
        # All real state is carried in the session; this is just the clock tick.
        tick_msg = Content(
            parts=[Part(text=f"cycle={cycle} ts={datetime.utcnow().isoformat()}")],
            role="user",
        )

        # State persistence works via event.actions.state_delta, not via manual
        # session manipulation. Each BaseAgent yields an Event that carries a
        # state_delta dict — ADK's append_event flushes those writes back to the
        # storage session automatically. No pre/post session mutation needed here.
        async for event in self._runner.run_async(
            user_id=self.USER_ID,
            session_id=self.SESSION_ID,
            new_message=tick_msg,
        ):
            author = getattr(event, "author", "?")
            if hasattr(event, "content") and event.content:
                parts = event.content.parts or []
                for part in parts:
                    text = getattr(part, "text", None)
                    if text and text.strip():
                        logger.debug("[%s] %s", author, text.strip()[:200])

        # After cycle completes, broadcast state to WebSocket clients
        await self._broadcast_state()

    # broadcast current state to WebSocket clients
    async def _broadcast_state(self):
        if not WEBSOCKET_ENABLED:
            return

        try:
            # Get current session state
            session = await self._session_service.get_session(
                app_name=self.APP_NAME,
                user_id=self.USER_ID,
                session_id=self.SESSION_ID
            )
            state = session.state if session else {}

            # Broadcast to WebSocket clients
            broadcast_state(state)
        except Exception as e:
            logger.debug(f"Could not broadcast state: {e}")

    # execute infinite full cycle 
    async def run_forever(self):
        init_tools(self._bridge)
        await self._create_session()

        set_ai_mode()
        logger.info("Arduino switched to AI mode")

        self._running      = True
        cycle              = 0
        consecutive_errors = 0

        logger.info("=== Fusion Pipeline Started ===")
        try:
            while self._running:
                cycle += 1
                logger.info("── Cycle %d ──────────────────────────────────", cycle)
                try:
                    await self._run_one_cycle(cycle)
                    
                    consecutive_errors = 0   # reset on any successful cycle
                except asyncio.CancelledError:
                    raise
                except Exception as exc:
                    consecutive_errors += 1
                    logger.error(
                        "Cycle %d error (%d/%d): %s",
                        cycle, consecutive_errors,
                        self._max_consecutive_errors, exc,
                        exc_info=True,
                    )
                    if consecutive_errors >= self._max_consecutive_errors:
                        logger.critical(
                            "%d consecutive failures — unrecoverable, shutting down",
                            self._max_consecutive_errors,
                        )
                        self._running = False
                    else:
                        await asyncio.sleep(2.0)

        except asyncio.CancelledError:
            logger.info("Pipeline cancelled")
        finally:
            await self._shutdown()
 
    # switches to backup
    async def _shutdown(self):
        logger.info("Shutting down — switching Arduino to auto/backup mode")
        try:
            set_backup()
        except Exception as exc:
            logger.warning("Could not switch to backup mode: %s", exc)
        self._running = False
        logger.info("=== Fusion Pipeline Stopped ===")
 
    # stops loop fully
    def stop(self):
        self._running = False